#!/usr/bin/env python3
"""
Comprehensive batch fix for all remaining autogenerated endpoint wrapper docstrings.
Processes all API endpoint files and replaces "Autogenerated wrapper for" docstrings
with comprehensive Google-style format.
"""

import re
from pathlib import Path
from re import Match


def generate_docstring(func_name: str, api_path: str) -> str:
    """Generate comprehensive Google-style docstring from function name and API path."""
    # Convert function name to operation title
    words = func_name.split("_")
    operation = " ".join(w.capitalize() for w in words)

    # Generate docstring
    docstring = f'''"""{operation}.

    Send a request to {api_path}. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """'''

    return docstring


def fix_file(filepath: Path) -> int:
    """Fix all autogenerated docstrings in a single file. Returns count of fixes."""
    try:
        content = filepath.read_text(encoding="utf-8")
    except Exception as e:
        print(f"  ERROR reading {filepath.name}: {e}")
        return 0

    original_content = content
    fixes = 0

    # Pattern to match function definitions with "Autogenerated wrapper" docstrings
    # This matches: def func_name(...) -> Any:\n    """Autogenerated wrapper for ``/path``."""
    pattern = r'(def\s+(\w+)\([^)]*\)\s*->\s*Any:)\s*"""Autogenerated wrapper for\s*``([^`]+)``\."""'

    def replacer(match: Match) -> str:
        nonlocal fixes
        func_def = match.group(1)
        func_name = match.group(2)
        api_path = match.group(3)

        new_docstring = generate_docstring(func_name, api_path)
        fixes += 1

        return f"{func_def}\n    {new_docstring}"

    # Apply replacements
    new_content = re.sub(pattern, replacer, content)

    # Write back if changed
    if new_content != original_content:
        try:
            filepath.write_text(new_content, encoding="utf-8")
            return fixes
        except Exception as e:
            print(f"  ERROR writing {filepath.name}: {e}")
            return 0

    return 0


def main():
    """Process all API endpoint files."""
    api_calls_root = Path("src/britecore_sdk/api/api_calls")
    total_fixes = 0

    if not api_calls_root.exists():
        print(f"ERROR: {api_calls_root} not found")
        return

    # Process v1 and v2 directories
    for version_dir in sorted(api_calls_root.glob("v*")):
        if not version_dir.is_dir():
            continue

        print(f"\nProcessing {version_dir.name}:")
        version_fixes = 0

        for module_file in sorted(version_dir.glob("*.py")):
            if module_file.name in ["__init__.py"]:
                continue

            module_fixes = fix_file(module_file)
            if module_fixes > 0:
                print(f"  ✓ {module_file.name}: {module_fixes} docstrings fixed")
                version_fixes += module_fixes

        total_fixes += version_fixes
        if version_fixes == 0:
            print("  (no changes)")

    print(f"\n{'=' * 60}")
    print(f"TOTAL: {total_fixes} autogenerated docstrings fixed")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
