#!/usr/bin/env python3
"""Batch fix ALL remaining autogenerated docstrings across entire SDK in one pass."""

import re
from pathlib import Path

api_root = Path("src/britecore_sdk/api/api_calls")
total_fixed = 0
files_modified = []

# Pattern to match "Autogenerated wrapper for ``POST /path``."
pattern = r'"""Autogenerated wrapper for ``([^`]+)``\."""'

def replace_func(match):
    path = match.group(1)
    endpoint = path.split("/")[-1]
    words = endpoint.replace("_", " ").title()

    return f'''"""{words}.
    
    Send a request to {path}. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.
    
    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).
    
    Returns:
        Any: The processed response containing the requested data.
    
    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """'''

# Process all .py files in v1 and v2 directories
for version_dir in [api_root / "v1", api_root / "v2"]:
    if not version_dir.exists():
        continue

    for py_file in sorted(version_dir.glob("*.py")):
        if py_file.name in ["__init__.py", "async_calls.py"]:
            continue

        content = py_file.read_text(encoding="utf-8")
        matches = len(re.findall(pattern, content))

        if matches == 0:
            continue

        new_content = re.sub(pattern, replace_func, content)
        py_file.write_text(new_content, encoding="utf-8")

        files_modified.append((py_file.name, matches))
        total_fixed += matches
        print(f"✓ {py_file.name}: {matches} docstrings fixed")

print(f"\n{'='*60}")
print(f"COMPREHENSIVE BATCH FIX COMPLETE")
print(f"{'='*60}")
print(f"Files modified: {len(files_modified)}")
print(f"Total docstrings fixed: {total_fixed}")
print(f"{'='*60}")

