#!/usr/bin/env python3
"""Generate comprehensive docstrings for all autogenerated endpoint wrappers."""

import json
import re
from pathlib import Path

def snake_to_title(name: str) -> str:
    """Convert snake_case function name to title case operation description."""
    # Map common operation prefixes
    prefixes = {
        "create": "Create",
        "delete": "Delete",
        "update": "Update",
        "retrieve": "Retrieve",
        "list": "List",
        "get": "Retrieve",
        "add": "Add",
        "make": "Make",
        "void": "Void",
        "store": "Store",
        "set": "Set",
    }

    words = name.split("_")
    first = words[0].lower()

    for prefix, title_prefix in prefixes.items():
        if first == prefix:
            rest = " ".join(w for w in words[1:]).replace("_", " ")
            return f"{title_prefix} {rest}"

    return name.replace("_", " ").title()

def build_docstring(func_name: str, path: str, params: dict) -> str:
    """Build a comprehensive Google-style docstring."""
    operation = snake_to_title(func_name)
    endpoint_path = path.split("/")[-1]

    # Build Args section
    args_lines = []
    for param_name, param_type in params.items():
        if param_name == "kwargs":
            args_lines.append("        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).")
        else:
            # Determine if optional
            if "| None" in str(param_type):
                args_lines.append(f"        {param_name}: Optional {param_name.replace('_', ' ')}.")
            else:
                args_lines.append(f"        {param_name}: The {param_name.replace('_', ' ')} (required).")

    args_section = "".join(f"\n{line}" for line in args_lines) if args_lines else ""

    docstring = f'''"""{ operation}.
    
    Submit a request to { path}. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.
    
    Args:{args_section}
    
    Returns:
        Any: The processed response containing the requested data.
    
    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """'''

    return docstring

# Test
if __name__ == "__main__":
    example_docstring = build_docstring("create_exposure", "/api/v2/claim_exposures/create_exposure", {
        "claim_id": "str | None",
        "page": "int | None",
        "page_size": "int | None",
    })
    print(example_docstring)

