from json import loads
from logging import Logger
from typing import Any, Unpack

from urllib3 import BaseHTTPResponse, HTTPResponse

from britecore_sdk import BritecoreError, logger
from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)
from britecore_sdk.models.contact import ROLETYPES

LOGGER: Logger = logger
API_CLIENT: BritecoreAPIClient = api_client


def retrieve_contact_list(
    search_str: str,
    search_filter: ROLETYPES | None = "Named Insured",
    current_page: str | None = "1",
    page_size: str | None = "10",
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """
    Retrieve a list of contacts based on search criteria.

    This function performs a contact search operation using the provided
    search string and optional filters. It constructs a request payload with
    the specified parameters and sends it to the API endpoint for contact
    retrieval.

    Parameters:
        search_str: The string to search for in contact records
        search_filter: The filter type to apply to the search (default: "Named Insured")
        current_page: The page number to retrieve (default: "1")
        page_size: The number of records per page (default: "10")
        **kwargs: Additional request parameters to pass to the API client

    Returns:
        A list of contact records matching the search criteria

    Raises:
        Any exceptions raised by the underlying API client or HTTP request
    """
    contact_request_json: dict[str, str | None] = {
        "searchString": search_str,
        "filter": search_filter,
        "currentPage": current_page,
        "pageSize": page_size,
    }

    LOGGER.debug("Getting search results")

    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path="/api/v1/contacts/retrieveContactList",
        json={k: v for k, v in contact_request_json.items() if v is not None},
        **kwargs,
    )

    if request_result is None or not hasattr(request_result, "data"):
        raise BritecoreError.NoDataReturned("No response from contact list API")

    contact_json: Any = loads(request_result.data.decode("utf-8"))

    return contact_json["records"]


# --- Autogenerated spec wrappers ---


def lookupcontactbyname(
    role: str | None = None,
    name: str | None = None,
    role_type: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/contacts/lookupContactByName``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "role": role,
        "name": name,
        "role_type": role_type,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/contacts/lookupContactByName",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/contacts/lookupContactByName"
    )


def retrieveaddressinfofromzip(
    zip: str | None = None,
    addressLine1: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/contacts/retrieveAddressInfoFromZip``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "zip": zip,
        "addressLine1": addressLine1,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/contacts/retrieveAddressInfoFromZip",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/contacts/retrieveAddressInfoFromZip"
    )


def retrieveaspectdata(
    roleId: str | None = None,
    hasPermissions: str | None = None,
    id: str | None = None,
    all: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/contacts/retrieveAspectData``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "roleId": roleId,
        "hasPermissions": hasPermissions,
        "id": id,
        "all": all,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/contacts/retrieveAspectData",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/contacts/retrieveAspectData"
    )


def storenewcontact(
    content: dict[str, Any] | None = None,
    role: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/contacts/storeNewContact``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "content": content,
        "role": role,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/contacts/storeNewContact",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/contacts/storeNewContact"
    )


def storeroles(
    contactId: str | None = None,
    e2ValDisallow: str | None = None,
    quotingRestriction: dict[str, Any] | None = None,
    agencyGroup: dict[str, Any] | None = None,
    defaultAgency: str | None = None,
    roleId: str | None = None,
    naicNumber: dict[str, Any] | None = None,
    sweepAccount: dict[str, Any] | None = None,
    notices: dict[str, Any] | None = None,
    interestContent: dict[str, Any] | None = None,
    loginInformation: dict[str, Any] | None = None,
    producerNumber: dict[str, Any] | None = None,
    agencies: dict[str, Any] | None = None,
    agencyInactive: str | None = None,
    commissionStructure: dict[str, Any] | None = None,
    commissionPayment: dict[str, Any] | None = None,
    termination: dict[str, Any] | None = None,
    agencyNumber: dict[str, Any] | None = None,
    defaultSurplusLinesProducer: dict[str, Any] | None = None,
    paymentsIssued: dict[str, Any] | None = None,
    vendorNumber: dict[str, Any] | None = None,
    creditScoreAccount: dict[str, Any] | None = None,
    agencyGroupNumber: dict[str, Any] | None = None,
    personalInformation: dict[str, Any] | None = None,
    agencyDates: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/contacts/storeRoles``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "contactId": contactId,
        "e2ValDisallow": e2ValDisallow,
        "quotingRestriction": quotingRestriction,
        "agencyGroup": agencyGroup,
        "defaultAgency": defaultAgency,
        "roleId": roleId,
        "naicNumber": naicNumber,
        "sweepAccount": sweepAccount,
        "notices": notices,
        "interestContent": interestContent,
        "loginInformation": loginInformation,
        "producerNumber": producerNumber,
        "agencies": agencies,
        "agencyInactive": agencyInactive,
        "commissionStructure": commissionStructure,
        "commissionPayment": commissionPayment,
        "termination": termination,
        "agencyNumber": agencyNumber,
        "defaultSurplusLinesProducer": defaultSurplusLinesProducer,
        "paymentsIssued": paymentsIssued,
        "vendorNumber": vendorNumber,
        "creditScoreAccount": creditScoreAccount,
        "agencyGroupNumber": agencyGroupNumber,
        "personalInformation": personalInformation,
        "agencyDates": agencyDates,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/contacts/storeRoles",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/contacts/storeRoles"
    )


__all__ = [
    "lookupcontactbyname",
    "retrieveaddressinfofromzip",
    "retrieveaspectdata",
    "storenewcontact",
    "storeroles",
]
