"""BriteCore V1 deliverables API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_deliverable(
    claim_loss_date: str | None = None,
    print_state: str | None = None,
    return_premium_id: str | None = None,
    filepath: str | None = None,
    invoice_id: str | None = None,
    go_date: str | None = None,
    reference_type: str | None = None,
    claim_id: str | None = None,
    claim_number: str | None = None,
    delay_print_days: int | None = None,
    reason: str | None = None,
    proc_date: str | None = None,
    location_id: str | None = None,
    revision_id: str | None = None,
    deliverable_type: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/deliverables/create_deliverable``."""
    request_json: dict[str, Any] = {
        "claim_loss_date": claim_loss_date,
        "print_state": print_state,
        "return_premium_id": return_premium_id,
        "filepath": filepath,
        "invoice_id": invoice_id,
        "go_date": go_date,
        "reference_type": reference_type,
        "claim_id": claim_id,
        "claim_number": claim_number,
        "delay_print_days": delay_print_days,
        "reason": reason,
        "proc_date": proc_date,
        "location_id": location_id,
        "revision_id": revision_id,
        "deliverable_type": deliverable_type,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/deliverables/create_deliverable",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/deliverables/create_deliverable"
    )


__all__ = [
    "create_deliverable",
]
