"""BriteCore V1 policies API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---


def getinspection(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/policies/getInspection``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/policies/getInspection",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/policies/getInspection"
    )


def getinspectionprimarycoverageoptions(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/policies/getInspectionPrimaryCoverageOptions``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/policies/getInspectionPrimaryCoverageOptions",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/policies/getInspectionPrimaryCoverageOptions"
    )


def newcustomdeliverable(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/policies/newCustomDeliverable``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/policies/newCustomDeliverable",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/policies/newCustomDeliverable"
    )


def retrievepropertyinfofromzip(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/policies/retrievePropertyInfoFromZip``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/policies/retrievePropertyInfoFromZip",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/policies/retrievePropertyInfoFromZip"
    )


def storensf(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v1/policies/storeNSF``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v1/policies/storeNSF",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v1/policies/storeNSF"
    )


__all__ = [
    "getinspection",
    "getinspectionprimarycoverageoptions",
    "newcustomdeliverable",
    "retrievepropertyinfofromzip",
    "storensf",
]
