"""BriteCore V1 policies API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def getinspection(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Getinspection.

    Send a request to POST /api/v1/policies/getInspection. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/policies/getInspection",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/policies/getInspection"
    )


def getinspectionprimarycoverageoptions(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Getinspectionprimarycoverageoptions.

    Send a request to POST /api/v1/policies/getInspectionPrimaryCoverageOptions. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/policies/getInspectionPrimaryCoverageOptions",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/policies/getInspectionPrimaryCoverageOptions"
    )


def newcustomdeliverable(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Newcustomdeliverable.

    Send a request to POST /api/v1/policies/newCustomDeliverable. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/policies/newCustomDeliverable",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/policies/newCustomDeliverable"
    )


def retrievepropertyinfofromzip(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrievepropertyinfofromzip.

    Send a request to POST /api/v1/policies/retrievePropertyInfoFromZip. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/policies/retrievePropertyInfoFromZip",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/policies/retrievePropertyInfoFromZip"
    )


def storensf(
    json_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Storensf.

    Send a request to POST /api/v1/policies/storeNSF. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "json_dict": json_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v1/policies/storeNSF",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v1/policies/storeNSF"
    )


__all__ = [
    "getinspection",
    "getinspectionprimarycoverageoptions",
    "newcustomdeliverable",
    "retrievepropertyinfofromzip",
    "storensf",
]
