"""BriteCore V2 auth API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---

def retrieve_permission_levels(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/auth/retrieve_permission_levels``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/auth/retrieve_permission_levels",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/auth/retrieve_permission_levels")


__all__ = [
    "retrieve_permission_levels",
]
