"""BriteCore V2 claim_exposures API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def add_recovery(
    claim_id: str | None = None,
    recovery_details: dict[str, Any] | None = None,
    api_key: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    reserve_details: Any | None = None,
    exposure_id: Any | None = None,
    payment_details: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add recovery information to a claim exposure.

    Register recovery details for a claim exposure via ``POST /api/v2/claim_exposures/add_recovery``.
    Includes optional reserve details and payment information. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        recovery_details: Recovery details payload (required).
        api_key: Optional API key for authentication override.
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        reserve_details: Optional reserve information.
        exposure_id: Optional exposure identifier reference.
        payment_details: Optional payment information.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing recovery information.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "recovery_details": recovery_details,
        "api_key": api_key,
        "page": page,
        "page_size": page_size,
        "reserve_details": reserve_details,
        "exposure_id": exposure_id,
        "payment_details": payment_details,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/add_recovery",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/add_recovery"
    )


def add_recovery_reserve(
    claim_id: str | None = None,
    api_key: str | None = None,
    recovery_reserve_details: dict[str, Any] | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add recovery reserve to a claim exposure.

    Register recovery reserve information for a claim via
    ``POST /api/v2/claim_exposures/add_recovery_reserve``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        api_key: Optional API key for authentication override.
        recovery_reserve_details: Recovery reserve details payload.
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing recovery reserve information.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "api_key": api_key,
        "recovery_reserve_details": recovery_reserve_details,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/add_recovery_reserve",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/add_recovery_reserve"
    )


def add_reserve(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add reserve to a claim exposure.

    Register reserve information for a claim exposure via
    ``POST /api/v2/claim_exposures/add_reserve``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing reserve information.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/add_reserve",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/add_reserve"
    )


def create_exposure(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create a new claim exposure.

    Register a new exposure for a claim via ``POST /api/v2/claim_exposures/create_exposure``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing newly created exposure data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/create_exposure",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/create_exposure"
    )


def delete_exposure(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete a claim exposure.

    Remove an exposure from a claim via ``POST /api/v2/claim_exposures/delete_exposure``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming deletion.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/delete_exposure",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/delete_exposure"
    )


def get_accounting_data(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve accounting data for a claim.

    Get accounting information for a claim exposure via
    ``POST /api/v2/claim_exposures/get_accounting_data``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing accounting data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_accounting_data"
    )


def get_accounting_loss_details(
    api_key: str | None = None,
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve accounting loss details for a claim.

    Get detailed accounting loss information for a claim via
    ``POST /api/v2/claim_exposures/get_accounting_loss_details``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        api_key: Optional API key for authentication override.
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing accounting loss details.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "api_key": api_key,
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_accounting_loss_details",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_accounting_loss_details"
    )


def get_accounting_overview(
    api_key: str | None = None,
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve accounting overview for a claim.

    Get an overview of accounting information for a claim via
    ``POST /api/v2/claim_exposures/get_accounting_overview``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        api_key: Optional API key for authentication override.
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing accounting overview.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "api_key": api_key,
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_accounting_overview",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_accounting_overview"
    )


def get_accounting_recoveries_data(
    api_key: str | None = None,
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve accounting recovery data for a claim.

    Get accounting recovery information for a claim via
    ``POST /api/v2/claim_exposures/get_accounting_recoveries_data``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        api_key: Optional API key for authentication override.
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing accounting recovery data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "api_key": api_key,
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_accounting_recoveries_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/claim_exposures/get_accounting_recoveries_data",
    )


def get_broken_limits(
    claim_id: str | None = None,
    instance: Any | None = None,
    type: Any | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve broken coverage limits for a claim.

    Get information about coverage limits that have been exceeded for a claim via
    ``POST /api/v2/claim_exposures/get_broken_limits``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        instance: Optional instance filter.
        type: Optional limit type filter.
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing broken limits information.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "instance": instance,
        "type": type,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_broken_limits",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_broken_limits"
    )


def get_coverage_accounting_data(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve coverage accounting data for a claim.

    Get accounting information by coverage for a claim via
    ``POST /api/v2/claim_exposures/get_coverage_accounting_data``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing coverage accounting data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_coverage_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_coverage_accounting_data"
    )


def get_exposure_accounting_data(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve exposure accounting data for a claim.

    Get accounting information by exposure for a claim via
    ``POST /api/v2/claim_exposures/get_exposure_accounting_data``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing exposure accounting data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_exposure_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_exposure_accounting_data"
    )


def get_exposure_transactions(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve transactions for a claim exposure.

    Get transaction history for a claim exposure via
    ``POST /api/v2/claim_exposures/get_exposure_transactions``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing exposure transaction data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_exposure_transactions",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_exposure_transactions"
    )


def get_payment(
    claim_id: str | None = None,
    payment_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve payment details for a claim exposure.

    Get payment information for a specific claim exposure payment via
    ``POST /api/v2/claim_exposures/get_payment``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        payment_id: The payment identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing payment details.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "payment_id": payment_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/get_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/get_payment"
    )


def list_exposures(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List all exposures for a claim.

    Retrieve all exposures associated with a claim via
    ``POST /api/v2/claim_exposures/list_exposures``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing a list of exposures.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/list_exposures",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/list_exposures"
    )


def make_multi_exposures_payment(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Make payment across multiple exposures for a claim.

    Submit a payment that applies to multiple exposures in a claim via
    ``POST /api/v2/claim_exposures/make_multi_exposures_payment``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming payment.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/make_multi_exposures_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/make_multi_exposures_payment"
    )


def make_payment(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Make payment for a claim exposure.

    Submit a payment for a claim exposure via ``POST /api/v2/claim_exposures/make_payment``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming payment.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/make_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/make_payment"
    )


def update_payment(
    claim_id: str | None = None,
    payment_details: dict[str, Any] | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update payment information for a claim exposure.

    Modify payment details for a claim exposure via ``POST /api/v2/claim_exposures/update_payment``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        payment_details: Updated payment details payload.
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response with updated payment information.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "payment_details": payment_details,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/update_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/update_payment"
    )


def void_transaction(
    claim_id: str | None = None,
    page: int | None = None,
    page_size: int | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Void a transaction for a claim exposure.

    Cancel/void a transaction for a claim exposure via
    ``POST /api/v2/claim_exposures/void_transaction``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier (required).
        page: Optional pagination page number.
        page_size: Optional pagination page size.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming void.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
        "page": page,
        "page_size": page_size,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_exposures/void_transaction",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_exposures/void_transaction"
    )


__all__ = [
    "add_recovery",
    "add_recovery_reserve",
    "add_reserve",
    "create_exposure",
    "delete_exposure",
    "get_accounting_data",
    "get_accounting_loss_details",
    "get_accounting_overview",
    "get_accounting_recoveries_data",
    "get_broken_limits",
    "get_coverage_accounting_data",
    "get_exposure_accounting_data",
    "get_exposure_transactions",
    "get_payment",
    "list_exposures",
    "make_multi_exposures_payment",
    "make_payment",
    "update_payment",
    "void_transaction",
]
