"""BriteCore V2 claim_catastrophes API endpoint wrappers.

Manage catastrophe associations with claims including natural disasters and major events.
"""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_catastrophe(
    catastrophe: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create a new catastrophe record.

    Submit a catastrophe payload to register a catastrophe event via
    ``POST /api/v2/claim_catastrophes/create_catastrophe``. Returns processed result
    from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        catastrophe: The catastrophe payload containing event details and identification.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the newly created catastrophe data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"catastrophe": catastrophe}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/create_catastrophe",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_catastrophes/create_catastrophe"
    )


def delete_catastrophe(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete a catastrophe record.

    Remove a catastrophe via ``POST /api/v2/claim_catastrophes/delete_catastrophe``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        id: The catastrophe identifier to delete.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming deletion.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/delete_catastrophe",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_catastrophes/delete_catastrophe"
    )


def get_applicable_catastrophes(
    claim_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve catastrophes applicable to a claim.

    Query applicable catastrophe events for a claim via
    ``POST /api/v2/claim_catastrophes/get_applicable_catastrophes``. Returns processed result
    from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        claim_id: The claim identifier to retrieve applicable catastrophes for.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing a list of applicable catastrophes.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"claim_id": claim_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/get_applicable_catastrophes",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/claim_catastrophes/get_applicable_catastrophes",
    )


def get_catastrophe(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve a specific catastrophe record.

    Query a single catastrophe via ``POST /api/v2/claim_catastrophes/get_catastrophe``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        id: The catastrophe identifier to retrieve.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the catastrophe data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/get_catastrophe",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_catastrophes/get_catastrophe"
    )


def list_catastrophes(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve all catastrophe records.

    Query all available catastrophes via ``POST /api/v2/claim_catastrophes/list_catastrophes``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing a list of all catastrophes.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/list_catastrophes",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_catastrophes/list_catastrophes"
    )


def update_catastrophe(
    catastrophe: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update an existing catastrophe record.

    Submit updated catastrophe data via ``POST /api/v2/claim_catastrophes/update_catastrophe``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        catastrophe: The catastrophe payload containing the catastrophe id and updated fields.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the updated catastrophe data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"catastrophe": catastrophe}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_catastrophes/update_catastrophe",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_catastrophes/update_catastrophe"
    )


__all__ = [
    "create_catastrophe",
    "delete_catastrophe",
    "get_applicable_catastrophes",
    "get_catastrophe",
    "list_catastrophes",
    "update_catastrophe",
]
