"""BriteCore V2 claim_estimations API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def cancel_claim_estimation(
    estimation_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Cancel Claim Estimation.

    Send a request to POST /api/v2/claim_estimations/cancel_claim_estimation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "estimation_id": estimation_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_estimations/cancel_claim_estimation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_estimations/cancel_claim_estimation"
    )


def get_claim_estimation(
    estimation_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Claim Estimation.

    Send a request to POST /api/v2/claim_estimations/get_claim_estimation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "estimation_id": estimation_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_estimations/get_claim_estimation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_estimations/get_claim_estimation"
    )


def list_claim_estimations(
    claim_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Claim Estimations.

    Send a request to POST /api/v2/claim_estimations/list_claim_estimations. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_id": claim_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_estimations/list_claim_estimations",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_estimations/list_claim_estimations"
    )


def request_claim_estimation(
    assignment_type: str | None = None,
    claim_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Request Claim Estimation.

    Send a request to POST /api/v2/claim_estimations/request_claim_estimation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "assignment_type": assignment_type,
        "claim_id": claim_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_estimations/request_claim_estimation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_estimations/request_claim_estimation"
    )


def update_claim_estimation(
    claim_estimation: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Claim Estimation.

    Send a request to POST /api/v2/claim_estimations/update_claim_estimation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "claim_estimation": claim_estimation,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_estimations/update_claim_estimation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_estimations/update_claim_estimation"
    )


__all__ = [
    "cancel_claim_estimation",
    "get_claim_estimation",
    "list_claim_estimations",
    "request_claim_estimation",
    "update_claim_estimation",
]
