"""BriteCore V2 claim_properties API endpoint wrappers."""

from __future__ import annotations

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client


def _coerce_claim_property_payload(claim_property: Any | None) -> Any | None:
    """Accept model instances and convert them to request-safe dict payloads."""
    if claim_property is None:
        return None
    if hasattr(claim_property, "to_dict") and callable(claim_property.to_dict):
        return claim_property.to_dict()
    return claim_property


# --- Autogenerated spec wrappers ---


def create_claim_property(
    claim_property: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Claim Property.

    POST /api/v2/claim_properties/create_claim_property
    """
    request_json: dict[str, Any] = {
        "claim_property": _coerce_claim_property_payload(claim_property)
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_properties/create_claim_property",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_properties/create_claim_property"
    )


def delete_claim_property(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Claim Property.

    POST /api/v2/claim_properties/delete_claim_property
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_properties/delete_claim_property",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_properties/delete_claim_property"
    )


def get_claim_properties(
    claim_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Claim Properties.

    POST /api/v2/claim_properties/get_claim_properties
    """
    request_json: dict[str, Any] = {"claim_id": claim_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_properties/get_claim_properties",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_properties/get_claim_properties"
    )


def get_claim_property(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Claim Property.

    POST /api/v2/claim_properties/get_claim_property
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_properties/get_claim_property",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_properties/get_claim_property"
    )


def update_claim_property(
    claim_property: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Claim Property.

    POST /api/v2/claim_properties/update_claim_property
    """
    request_json: dict[str, Any] = {
        "claim_property": _coerce_claim_property_payload(claim_property)
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_properties/update_claim_property",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_properties/update_claim_property"
    )


__all__ = [
    "create_claim_property",
    "delete_claim_property",
    "get_claim_properties",
    "get_claim_property",
    "update_claim_property",
]
