"""BriteCore V2 claim_dates API endpoint wrappers.

Manage important dates associated with claims including loss date, report date,
and other critical claim timeline information.
"""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_claim_date(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create a new date entry for a claim. (POST /api/v2/claim_dates/create_claim_date)."""
    request_json: dict[str, Any] = {"data": data}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_dates/create_claim_date",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_dates/create_claim_date"
    )


def delete_claim_date(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete a claim date entry. (POST /api/v2/claim_dates/delete_claim_date)."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_dates/delete_claim_date",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_dates/delete_claim_date"
    )


def list_claim_dates(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve all date entries for a claim. (POST /api/v2/claim_dates/list_claim_dates)."""
    request_json: dict[str, Any] = {"data": data}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_dates/list_claim_dates",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_dates/list_claim_dates"
    )


def update_claim_date(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update an existing claim date entry. (POST /api/v2/claim_dates/update_claim_date)."""
    request_json: dict[str, Any] = {"data": data}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/claim_dates/update_claim_date",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/claim_dates/update_claim_date"
    )


__all__ = [
    "create_claim_date",
    "delete_claim_date",
    "list_claim_dates",
    "update_claim_date",
]
