"""BriteCore V2 claim_exposures API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---

def add_recovery(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/add_recovery``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/add_recovery",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/add_recovery")


def add_recovery_reserve(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/add_recovery_reserve``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/add_recovery_reserve",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/add_recovery_reserve")


def add_reserve(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/add_reserve``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/add_reserve",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/add_reserve")


def create_exposure(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/create_exposure``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/create_exposure",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/create_exposure")


def delete_exposure(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/delete_exposure``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/delete_exposure",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/delete_exposure")


def get_accounting_data(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_accounting_data``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_accounting_data")


def get_accounting_loss_details(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_accounting_loss_details``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_accounting_loss_details",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_accounting_loss_details")


def get_accounting_overview(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_accounting_overview``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_accounting_overview",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_accounting_overview")


def get_accounting_recoveries_data(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_accounting_recoveries_data``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_accounting_recoveries_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_accounting_recoveries_data")


def get_broken_limits(
    instance: Any | None = None,
    type: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_broken_limits``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "instance": instance,
        "type": type,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_broken_limits",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_broken_limits")


def get_coverage_accounting_data(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_coverage_accounting_data``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_coverage_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_coverage_accounting_data")


def get_exposure_accounting_data(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_exposure_accounting_data``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_exposure_accounting_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_exposure_accounting_data")


def get_exposure_transactions(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_exposure_transactions``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_exposure_transactions",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_exposure_transactions")


def get_payment(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/get_payment``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/get_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/get_payment")


def list_exposures(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/list_exposures``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/list_exposures",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/list_exposures")


def make_multi_exposures_payment(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/make_multi_exposures_payment``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/make_multi_exposures_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/make_multi_exposures_payment")


def make_payment(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/make_payment``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/make_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/make_payment")


def update_payment(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/update_payment``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/update_payment",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/update_payment")


def void_transaction(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_exposures/void_transaction``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_exposures/void_transaction",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/claim_exposures/void_transaction")


__all__ = [
    "add_recovery",
    "add_recovery_reserve",
    "add_reserve",
    "create_exposure",
    "delete_exposure",
    "get_accounting_data",
    "get_accounting_loss_details",
    "get_accounting_overview",
    "get_accounting_recoveries_data",
    "get_broken_limits",
    "get_coverage_accounting_data",
    "get_exposure_accounting_data",
    "get_exposure_transactions",
    "get_payment",
    "list_exposures",
    "make_multi_exposures_payment",
    "make_payment",
    "update_payment",
    "void_transaction",
]
