"""BriteCore V2 claim_adjuster_assignment_configs API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---


def create_adjuster_assignment_config(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_adjuster_assignment_configs/create_adjuster_assignment_config``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_adjuster_assignment_configs/create_adjuster_assignment_config",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result,
        endpoint="/api/v2/claim_adjuster_assignment_configs/create_adjuster_assignment_config",
    )


def get_adjuster_assignment_config(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_adjuster_assignment_configs/get_adjuster_assignment_config``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_adjuster_assignment_configs/get_adjuster_assignment_config",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result,
        endpoint="/api/v2/claim_adjuster_assignment_configs/get_adjuster_assignment_config",
    )


def update_adjuster_assignment_config(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/claim_adjuster_assignment_configs/update_adjuster_assignment_config``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/claim_adjuster_assignment_configs/update_adjuster_assignment_config",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result,
        endpoint="/api/v2/claim_adjuster_assignment_configs/update_adjuster_assignment_config",
    )


__all__ = [
    "create_adjuster_assignment_config",
    "get_adjuster_assignment_config",
    "update_adjuster_assignment_config",
]
