"""BriteCore V2 coverages API endpoint wrappers."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

if TYPE_CHECKING:
    from britecore_sdk.models import BritecoreCoverage


def _coerce_coverage_payload(coverage: Any | None) -> Any | None:
    """Accept model instances and convert them to request-safe dict payloads."""
    if coverage is None:
        return None
    to_dict = getattr(coverage, "to_dict", None)
    if callable(to_dict):
        return to_dict()
    return coverage


def _coerce_coverages_payload(coverages: Any | None) -> Any | None:
    """Coerce a sequence of coverage models/dicts into API payload shape."""
    if coverages is None:
        return None
    if isinstance(coverages, list):
        return [_coerce_coverage_payload(item) for item in coverages]
    return coverages


# --- Autogenerated spec wrappers ---


def add_coverage(
    coverage: BritecoreCoverage | dict[str, Any] | Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add Coverage.

    POST /api/v2/coverages/add_coverage
    """
    request_json: dict[str, Any] = {"coverage": _coerce_coverage_payload(coverage)}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/add_coverage",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/add_coverage"
    )


def add_coverages(
    coverages: list[BritecoreCoverage | dict[str, Any]] | Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add Coverages.

    POST /api/v2/coverages/add_coverages
    """
    request_json: dict[str, Any] = {"coverages": _coerce_coverages_payload(coverages)}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/add_coverages",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/add_coverages"
    )


def add_sub_lines(
    sublines: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add Sub Lines.

    POST /api/v2/coverages/add_sub_lines
    """
    request_json: dict[str, Any] = {"sublines": sublines}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/add_sub_lines",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/add_sub_lines"
    )


def delete_coverage(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Coverage.

    POST /api/v2/coverages/delete_coverage
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/delete_coverage",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/delete_coverage"
    )


def delete_sub_line(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Sub Line.

    POST /api/v2/coverages/delete_sub_line
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/delete_sub_line",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/delete_sub_line"
    )


def list_all_coverages(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List All Coverages.

    POST /api/v2/coverages/list_all_coverages
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/list_all_coverages",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/list_all_coverages"
    )


def list_coverages(
    property_id: Any | None = None,
    quote_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Coverages.

    POST /api/v2/coverages/list_coverages
    """
    request_json: dict[str, Any] = {
        "property_id": property_id,
        "quote_id": quote_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/list_coverages",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/list_coverages"
    )


def list_sub_lines(
    property_id: Any | None = None,
    quote_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Sub Lines.

    POST /api/v2/coverages/list_sub_lines
    """
    request_json: dict[str, Any] = {
        "property_id": property_id,
        "quote_id": quote_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/list_sub_lines",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/list_sub_lines"
    )


def update_coverage(
    coverage: BritecoreCoverage | dict[str, Any] | Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Coverage.

    POST /api/v2/coverages/update_coverage
    """
    request_json: dict[str, Any] = {"coverage": _coerce_coverage_payload(coverage)}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/update_coverage",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/update_coverage"
    )


def update_coverages(
    coverages: list[BritecoreCoverage | dict[str, Any]] | Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Coverages.

    POST /api/v2/coverages/update_coverages
    """
    request_json: dict[str, Any] = {"coverages": _coerce_coverages_payload(coverages)}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/update_coverages",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/update_coverages"
    )


def update_revision_billing_schedule(
    policy_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Revision Billing Schedule.

    POST /api/v2/coverages/update_revision_billing_schedule
    """
    request_json: dict[str, Any] = {"policy_id": policy_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/coverages/update_revision_billing_schedule",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/coverages/update_revision_billing_schedule"
    )


__all__ = [
    "add_coverage",
    "add_coverages",
    "add_sub_lines",
    "delete_coverage",
    "delete_sub_line",
    "list_all_coverages",
    "list_coverages",
    "list_sub_lines",
    "update_coverage",
    "update_coverages",
    "update_revision_billing_schedule",
]
