"""BriteCore V2 custom_data API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def add_custom_data(
    data: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add Custom Data.

    Send a request to POST /api/v2/custom_data/add_custom_data. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "data": data,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/custom_data/add_custom_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/custom_data/add_custom_data"
    )


def delete_custom_data(
    ids: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Custom Data.

    Send a request to POST /api/v2/custom_data/delete_custom_data. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "ids": ids,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/custom_data/delete_custom_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/custom_data/delete_custom_data"
    )


def get_custom_data(
    reference_id: str | None = None,
    id: str | None = None,
    name: str | None = None,
    ids: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Custom Data.

    Send a request to POST /api/v2/custom_data/get_custom_data. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "reference_id": reference_id,
        "id": id,
        "name": name,
        "ids": ids,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/custom_data/get_custom_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/custom_data/get_custom_data"
    )


def summarize_custom_data(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Summarize Custom Data.

    Send a request to POST /api/v2/custom_data/summarize_custom_data. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/custom_data/summarize_custom_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/custom_data/summarize_custom_data"
    )


def update_custom_data(
    data: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Custom Data.

    Send a request to POST /api/v2/custom_data/update_custom_data. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "data": data,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/custom_data/update_custom_data",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/custom_data/update_custom_data"
    )


__all__ = [
    "add_custom_data",
    "delete_custom_data",
    "get_custom_data",
    "summarize_custom_data",
    "update_custom_data",
]
