"""BriteCore v2 Deliverables API endpoint wrappers.

This module provides wrappers for deliverable attachment lookups and
e-deliverable retrieval in the BriteCore v2 deliverables API.
"""

from logging import Logger
from typing import Any, Unpack

from urllib3 import BaseHTTPResponse, HTTPResponse

from britecore_sdk import logger
from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)
from britecore_sdk.exceptions import BritecoreError

LOGGER: Logger = logger
API_CLIENT: BritecoreAPIClient = api_client


def list_attachments(
    policy_id: str | None = None,
    revision_id: str | None = None,
    contact_id: str | None = None,
    print_date_from: str | None = None,
    print_date_to: str | None = None,
    print_state_ne: str | None = None,
    print_state: str | None = None,
    order_by: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List deliverable attachments for a policy, contact, or revision.

    This wrapper uses the supplied identifiers and optional print-state/date
    filters to call ``/api/v2/deliverables/list_attachments``. It returns the
    normalized ``process_result(...)`` payload for the attachment query and
    accepts ``RequestParameters`` overrides via ``**kwargs``.
    """
    local_env: dict[str, str | None] = {**locals()}
    if not policy_id and not contact_id and not revision_id:
        BritecoreError.MissingParameter("policy_id, contact_id or revision_id required")

    parameter_list: list[dict[str, str | None]] = [
        {"policy_id": policy_id},
        {"contact_id": contact_id},
        {"revision_id": revision_id},
    ]
    parameter_priority: list[str] = ["revision_id", "contact_id", "policy_id"]

    attachments_search: dict[str, str | None] = (
        api_client.multiple_parameter_verification(parameter_list, parameter_priority)
    )

    for _, (k, v) in enumerate(local_env.items()):
        if v and k not in parameter_priority:
            attachments_search.update({k: v})

    logger.debug("Getting attachments")

    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path="/api/v2/deliverables/list_attachments",
        json=attachments_search,
        **kwargs,
    )

    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/list_attachments"
    )


def get_attachment(file_id: str, **kwargs: Unpack[RequestParameters]) -> Any:
    """Retrieve a deliverable attachment by file identifier.

    This wrapper sends ``file_id`` to ``/api/v2/deliverables/get_attachment``
    and returns the normalized ``process_result(...)`` payload for the matching
    attachment record. ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    LOGGER.debug("Getting attachment '%s'", file_id)
    file_search: dict[str, str] = {"file_id": file_id}
    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_attachment", json=file_search, **kwargs
    )

    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_attachment"
    )


def get_edeliverables(
    date_from: str,
    date_to: str,
    unprocessed_only: bool | None = True,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve e-deliverables for a date range.

    This wrapper sends ``date_from``, ``date_to``, and ``unprocessed_only`` to
    ``/api/v2/deliverables/get_edeliverables`` and returns the normalized
    ``process_result(...)`` payload for the e-deliverable query.
    ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    required_json: dict[str, str | bool | None] = {
        "date_from": date_from,
        "date_to": date_to,
        "unprocessed_only": unprocessed_only,
    }

    LOGGER.debug("Getting E-Deliverables\n%s", required_json)

    result_request: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        "/api/v2/deliverables/get_edeliverables",
        json=required_json,
        **kwargs,
    )

    return API_CLIENT.process_result(result_request)


# --- Autogenerated spec wrappers ---


def delete_html_template(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/delete_html_template``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/delete_html_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/delete_html_template"
    )


def delete_static_resource(
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/delete_static_resource``."""
    request_json: dict[str, Any] = {
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/delete_static_resource",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/delete_static_resource"
    )


def expire_all_static_resources(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/expire_all_static_resources``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/expire_all_static_resources",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/expire_all_static_resources"
    )


def expire_static_resource(
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/expire_static_resource``."""
    request_json: dict[str, Any] = {
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/expire_static_resource",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/expire_static_resource"
    )


def getdeliverabledata(
    coverage_forms: list[str] | None = None,
    invoice_id: str | None = None,
    date_cursor: str | None = None,
    reason: str | None = None,
    state_id: str | None = None,
    revision_id: str | None = None,
    return_data: bool | None = None,
    deliverable_type: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/getDeliverableData``."""
    request_json: dict[str, Any] = {
        "coverage_forms": coverage_forms,
        "invoice_id": invoice_id,
        "date_cursor": date_cursor,
        "reason": reason,
        "state_id": state_id,
        "revision_id": revision_id,
        "return_data": return_data,
        "deliverable_type": deliverable_type,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/getDeliverableData",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/getDeliverableData"
    )


def get_all_html_templates(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_all_html_templates``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_all_html_templates",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_all_html_templates"
    )


def get_all_static_resources(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_all_static_resources``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_all_static_resources",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_all_static_resources"
    )


def get_dec(
    revision_id: str | None = None,
    reason: str | None = None,
    policy_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_dec``."""
    request_json: dict[str, Any] = {
        "revision_id": revision_id,
        "reason": reason,
        "policy_id": policy_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_dec",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_dec"
    )


def get_dynamic_fields(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_dynamic_fields``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_dynamic_fields",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_dynamic_fields"
    )


def get_edeliverables_by_id(
    ids: list[str] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_edeliverables_by_id``."""
    request_json: dict[str, Any] = {
        "ids": ids,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_edeliverables_by_id",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_edeliverables_by_id"
    )


def get_html_template(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_html_template``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_html_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_html_template"
    )


def get_pending_email_count(
    from_date: str | None = None,
    to_date: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_pending_email_count``."""
    request_json: dict[str, Any] = {
        "from_date": from_date,
        "to_date": to_date,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_pending_email_count",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_pending_email_count"
    )


def get_static_resource(
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/get_static_resource``."""
    request_json: dict[str, Any] = {
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/get_static_resource",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/get_static_resource"
    )


def index_edelivery_records(
    date_from: str | None = None,
    date_to: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/index_edelivery_records``."""
    request_json: dict[str, Any] = {
        "date_from": date_from,
        "date_to": date_to,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/index_edelivery_records",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/index_edelivery_records"
    )


def regenerate_combined_billing_statements(
    force_generation: Any | None = None,
    start_date: Any | None = None,
    end_date: Any | None = None,
    group_billing_number: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/regenerate_combined_billing_statements``."""
    request_json: dict[str, Any] = {
        "force_generation": force_generation,
        "start_date": start_date,
        "end_date": end_date,
        "group_billing_number": group_billing_number,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/regenerate_combined_billing_statements",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/deliverables/regenerate_combined_billing_statements",
    )


def remove_edelivery_records(
    date_from: str | None = None,
    date_to: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/remove_edelivery_records``."""
    request_json: dict[str, Any] = {
        "date_from": date_from,
        "date_to": date_to,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/remove_edelivery_records",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/remove_edelivery_records"
    )


def retrieve_available_document_options(
    location_abbr: str | None = None,
    location_name: str | None = None,
    location_id: str | None = None,
    module: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/retrieve_available_document_options``."""
    request_json: dict[str, Any] = {
        "location_abbr": location_abbr,
        "location_name": location_name,
        "location_id": location_id,
        "module": module,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/retrieve_available_document_options",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/deliverables/retrieve_available_document_options",
    )


def retrieve_files_for_entity(
    field: str | None = None,
    advanced_filters: list[str] | None = None,
    success: bool | None = None,
    allow_null_reference: bool | None = None,
    policy_number: str | None = None,
    messages: list[str] | None = None,
    ascending: bool | None = None,
    claim_number: str | None = None,
    Returns: str | None = None,
    reference_id: str | None = None,
    data: list[str] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/retrieve_files_for_entity``."""
    request_json: dict[str, Any] = {
        "-------": field,
        "advanced_filters": advanced_filters,
        "success": success,
        "allow_null_reference": allow_null_reference,
        "policy_number": policy_number,
        "messages": messages,
        "ascending": ascending,
        "claim_number": claim_number,
        "Returns": Returns,
        "reference_id": reference_id,
        "data": data,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/retrieve_files_for_entity",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/retrieve_files_for_entity"
    )


def retrieve_invoice_document(
    invoice_number: str | None = None,
    primary_insured: bool | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/retrieve_invoice_document``."""
    request_json: dict[str, Any] = {
        "invoice_number": invoice_number,
        "primary_insured": primary_insured,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/retrieve_invoice_document",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/retrieve_invoice_document"
    )


def save_html_template(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/save_html_template``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/save_html_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/save_html_template"
    )


def save_static_resource(
    url: str | None = None,
    expire_in: int | None = None,
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/save_static_resource``."""
    request_json: dict[str, Any] = {
        "url": url,
        "expire_in": expire_in,
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/save_static_resource",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/save_static_resource"
    )


def set_html_templates_locations(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/set_html_templates_locations``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/set_html_templates_locations",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/set_html_templates_locations"
    )


def update_edelivery_records(
    records: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/deliverables/update_edelivery_records``."""
    request_json: dict[str, Any] = {
        "records": records,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/deliverables/update_edelivery_records",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/deliverables/update_edelivery_records"
    )


__all__ = [
    "delete_html_template",
    "delete_static_resource",
    "expire_all_static_resources",
    "expire_static_resource",
    "getdeliverabledata",
    "get_all_html_templates",
    "get_all_static_resources",
    "get_dec",
    "get_dynamic_fields",
    "get_edeliverables_by_id",
    "get_html_template",
    "get_pending_email_count",
    "get_static_resource",
    "index_edelivery_records",
    "regenerate_combined_billing_statements",
    "remove_edelivery_records",
    "retrieve_available_document_options",
    "retrieve_files_for_entity",
    "retrieve_invoice_document",
    "save_html_template",
    "save_static_resource",
    "set_html_templates_locations",
    "update_edelivery_records",
]
