"""BriteCore V2 disputes API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---

def create_dispute(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/disputes/create_dispute``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/disputes/create_dispute",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/disputes/create_dispute")


def delete_dispute(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/disputes/delete_dispute``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/disputes/delete_dispute",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/disputes/delete_dispute")


def list_disputes(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/disputes/list_disputes``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/disputes/list_disputes",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/disputes/list_disputes")


def update_dispute(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/disputes/update_dispute``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/disputes/update_dispute",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/disputes/update_dispute")


__all__ = [
    "create_dispute",
    "delete_dispute",
    "list_disputes",
    "update_dispute",
]
