"""BriteCore V2 files API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def generate_download_url(
    expires_in: Any | None = None,
    file_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Generate Download Url (POST /api/v2/files/generate_download_url)."""
    request_json: dict[str, Any] = {
        "expires_in": expires_in,
        "file_id": file_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/files/generate_download_url",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/files/generate_download_url"
    )


def retrieve_active_file_objects(
    date_added_to: str | None = None,
    label: str | None = None,
    print_date_from: str | None = None,
    date_added_from: str | None = None,
    print_date_to: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve Active File Objects (POST /api/v2/files/retrieve_active_file_objects)."""
    request_json: dict[str, Any] = {
        "date_added_to": date_added_to,
        "label": label,
        "print_date_from": print_date_from,
        "date_added_from": date_added_from,
        "print_date_to": print_date_to,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/files/retrieve_active_file_objects",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/files/retrieve_active_file_objects"
    )


__all__ = [
    "generate_download_url",
    "retrieve_active_file_objects",
]
