"""BriteCore V2 geometries API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_geometry(
    geolocation: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Geometry.

    Send a request to POST /api/v2/geometries/create_geometry. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"geolocation": geolocation}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/create_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/create_geometry"
    )


def delete_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Geometry.

    Send a request to POST /api/v2/geometries/delete_geometry. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/delete_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/delete_geometry"
    )


def get_geometries(
    page: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Geometries.

    Send a request to POST /api/v2/geometries/get_geometries. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"page": page}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/get_geometries",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/get_geometries"
    )


def get_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Geometry.

    Send a request to POST /api/v2/geometries/get_geometry. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/get_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/get_geometry"
    )


def update_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Geometry.

    Send a request to POST /api/v2/geometries/update_geometry. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/update_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/update_geometry"
    )


__all__ = [
    "create_geometry",
    "delete_geometry",
    "get_geometries",
    "get_geometry",
    "update_geometry",
]
