"""BriteCore V2 geometries API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_geometry(
    geolocation: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Geometry (POST /api/v2/geometries/create_geometry)."""
    request_json: dict[str, Any] = {"geolocation": geolocation}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/create_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/create_geometry"
    )


def delete_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Geometry (POST /api/v2/geometries/delete_geometry)."""
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/delete_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/delete_geometry"
    )


def get_geometries(
    page: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Geometries (POST /api/v2/geometries/get_geometries)."""
    request_json: dict[str, Any] = {"page": page}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/get_geometries",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/get_geometries"
    )


def get_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Geometry (POST /api/v2/geometries/get_geometry)."""
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/get_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/get_geometry"
    )


def update_geometry(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Geometry (POST /api/v2/geometries/update_geometry)."""
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometries/update_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometries/update_geometry"
    )


__all__ = [
    "create_geometry",
    "delete_geometry",
    "get_geometries",
    "get_geometry",
    "update_geometry",
]
