"""BriteCore V2 geometry API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def get_zip_geometry(
    zip_code: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Zip Geometry.

    POST /api/v2/geometry/get_zip_geometry
    """
    request_json: dict[str, Any] = {
        "zip_code": zip_code,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/geometry/get_zip_geometry",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/geometry/get_zip_geometry"
    )


__all__ = [
    "get_zip_geometry",
]
