"""BriteCore V2 ingestion_job API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_ingestion_job(
    ingestion_job: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Ingestion Job.

    Send a request to POST /api/v2/ingestion_job/create_ingestion_job. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"ingestion_job": ingestion_job}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/ingestion_job/create_ingestion_job",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/ingestion_job/create_ingestion_job"
    )


def delete_ingestion_job(
    ingestion_job_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Ingestion Job.

    Send a request to POST /api/v2/ingestion_job/delete_ingestion_job. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"ingestion_job_id": ingestion_job_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/ingestion_job/delete_ingestion_job",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/ingestion_job/delete_ingestion_job"
    )


def execute_import(
    ingestion_job_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Execute Import.

    Send a request to POST /api/v2/ingestion_job/execute_import. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"ingestion_job_id": ingestion_job_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/ingestion_job/execute_import",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/ingestion_job/execute_import"
    )


def get_ingestion_job(
    ingestion_job_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Ingestion Job.

    Send a request to POST /api/v2/ingestion_job/get_ingestion_job. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"ingestion_job_id": ingestion_job_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/ingestion_job/get_ingestion_job",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/ingestion_job/get_ingestion_job"
    )


def list_ingestion_jobs(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Ingestion Jobs.

    Send a request to POST /api/v2/ingestion_job/list_ingestion_jobs. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/ingestion_job/list_ingestion_jobs",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/ingestion_job/list_ingestion_jobs"
    )


__all__ = [
    "create_ingestion_job",
    "delete_ingestion_job",
    "execute_import",
    "get_ingestion_job",
    "list_ingestion_jobs",
]
