"""BriteCore V2 named_insureds API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_named_insured(
    named_insured: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create a new named insured record.

    Submit a named_insured payload to register a new named insured on a policy
    via ``POST /api/v2/named_insureds/create_named_insured``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        named_insured: The named insured payload containing insured name, role, and contact information.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the newly created named insured data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"named_insured": named_insured}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/create_named_insured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/create_named_insured"
    )


def delete_named_insured(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete a named insured record by identifier.

    Use the named insured ``id`` to remove it from the system via
    ``POST /api/v2/named_insureds/delete_named_insured``. Returns processed
    result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        id: The named insured identifier to delete.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response confirming deletion.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error
            (e.g., NotFoundError if the named insured does not exist).
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/delete_named_insured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/delete_named_insured"
    )


def get_named_insured(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Named Insured.

    Send a request to POST /api/v2/named_insureds/get_named_insured. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/get_named_insured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/get_named_insured"
    )


def get_named_insured_by_id(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Named Insured By Id.

    Send a request to POST /api/v2/named_insureds/get_named_insured_by_id. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"data": data}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/get_named_insured_by_id",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/get_named_insured_by_id"
    )


def get_named_insureds(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Named Insureds.

    Send a request to POST /api/v2/named_insureds/get_named_insureds. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"data": data}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/get_named_insureds",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/get_named_insureds"
    )


def run_score(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Run Score.

    Send a request to POST /api/v2/named_insureds/run_score. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/run_score",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/run_score"
    )


def set_primary_insured(
    quote_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Set Primary Insured.

    Send a request to POST /api/v2/named_insureds/set_primary_insured. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"quote_id": quote_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/set_primary_insured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/set_primary_insured"
    )


def update_named_insured(
    named_insured: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update an existing named insured record.

    Submit a named_insured payload with updated information to modify an
    existing named insured via ``POST /api/v2/named_insureds/update_named_insured``.
    Returns processed result from ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        named_insured: The named insured payload containing the insured id and updated fields.
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the updated named insured data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error
            (e.g., NotFoundError if the named insured does not exist).
    """
    request_json: dict[str, Any] = {"named_insured": named_insured}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/named_insureds/update_named_insured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/named_insureds/update_named_insured"
    )


__all__ = [
    "create_named_insured",
    "delete_named_insured",
    "get_named_insured",
    "get_named_insured_by_id",
    "get_named_insureds",
    "run_score",
    "set_primary_insured",
    "update_named_insured",
]
