"""BriteCore V2 policy_types API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_policy_type_relation(
    relationship_type: str | None = None,
    policy_type_id: str | None = None,
    related_policy_type_name: str | None = None,
    related_line_name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/create_policy_type_relation``."""
    request_json: dict[str, Any] = {
        "relationship_type": relationship_type,
        "policy_type_id": policy_type_id,
        "related_policy_type_name": related_policy_type_name,
        "related_line_name": related_line_name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/create_policy_type_relation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/create_policy_type_relation"
    )


def get_coverage_type(
    coverage_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/get_coverage_type``."""
    request_json: dict[str, Any] = {"coverage_id": coverage_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/get_coverage_type",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/get_coverage_type"
    )


def list_available_coverages(
    quote_id: Any | None = None,
    risk_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/list_available_coverages``."""
    request_json: dict[str, Any] = {
        "quote_id": quote_id,
        "risk_id": risk_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/list_available_coverages",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/list_available_coverages"
    )


def list_available_sub_lines(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/list_available_sub_lines``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/list_available_sub_lines",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/list_available_sub_lines"
    )


def list_coverage_types(
    policy_type_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/list_coverage_types``."""
    request_json: dict[str, Any] = {"policy_type_id": policy_type_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/list_coverage_types",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/list_coverage_types"
    )


def list_filtered_policy_types(
    effective_date: Any | None = None,
    location_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/list_filtered_policy_types``."""
    request_json: dict[str, Any] = {
        "effective_date": effective_date,
        "location_id": location_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/list_filtered_policy_types",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/list_filtered_policy_types"
    )


def remove_policy_type_relations(
    relationship_type: str | None = None,
    policy_type_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/remove_policy_type_relations``."""
    request_json: dict[str, Any] = {
        "relationship_type": relationship_type,
        "policy_type_id": policy_type_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/remove_policy_type_relations",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/remove_policy_type_relations"
    )


def retrieve_policy_types(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/retrieve_policy_types``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/retrieve_policy_types",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/retrieve_policy_types"
    )


def update_quick_codes(
    policy_type_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/policy_types/update_quick_codes``."""
    request_json: dict[str, Any] = {"policy_type_id": policy_type_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/policy_types/update_quick_codes",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/policy_types/update_quick_codes"
    )


__all__ = [
    "create_policy_type_relation",
    "get_coverage_type",
    "list_available_coverages",
    "list_available_sub_lines",
    "list_coverage_types",
    "list_filtered_policy_types",
    "remove_policy_type_relations",
    "retrieve_policy_types",
    "update_quick_codes",
]
