"""BriteCore V2 premium_finance_companies API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create(
    premium_finance_company: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create.

    POST /api/v2/premium_finance_companies/create
    """
    request_json: dict[str, Any] = {"premium_finance_company": premium_finance_company}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/premium_finance_companies/create",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/create"
    )


def delete(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete.

    POST /api/v2/premium_finance_companies/delete
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/premium_finance_companies/delete",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/delete"
    )


def get(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get.

    POST /api/v2/premium_finance_companies/get
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/premium_finance_companies/get",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/get"
    )


def list_for_quote(
    quote_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List For Quote.

    POST /api/v2/premium_finance_companies/list_for_quote
    """
    request_json: dict[str, Any] = {"quote_id": quote_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/premium_finance_companies/list_for_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/list_for_quote"
    )


def update(
    premium_finance_company: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update.

    POST /api/v2/premium_finance_companies/update
    """
    request_json: dict[str, Any] = {"premium_finance_company": premium_finance_company}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/premium_finance_companies/update",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/update"
    )


__all__ = [
    "create",
    "delete",
    "get",
    "list_for_quote",
    "update",
]
