"""BriteCore V2 premium_finance_companies API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---


def create(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/premium_finance_companies/create``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/premium_finance_companies/create",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/create"
    )


def delete(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/premium_finance_companies/delete``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/premium_finance_companies/delete",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/delete"
    )


def get(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/premium_finance_companies/get``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/premium_finance_companies/get",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/get"
    )


def list_for_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/premium_finance_companies/list_for_quote``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/premium_finance_companies/list_for_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/list_for_quote"
    )


def update(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/premium_finance_companies/update``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/premium_finance_companies/update",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/premium_finance_companies/update"
    )


__all__ = [
    "create",
    "delete",
    "get",
    "list_for_quote",
    "update",
]
