"""BriteCore V2 prior_policies API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def list_prior_policies(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Prior Policies.

    POST /api/v2/prior_policies/list_prior_policies
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/prior_policies/list_prior_policies",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/prior_policies/list_prior_policies"
    )


def update_prior_policy(
    prior_policy: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Prior Policy.

    POST /api/v2/prior_policies/update_prior_policy
    """
    request_json: dict[str, Any] = {"prior_policy": prior_policy}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/prior_policies/update_prior_policy",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/prior_policies/update_prior_policy"
    )


__all__ = [
    "list_prior_policies",
    "update_prior_policy",
]
