"""BriteCore V2 quick_codes API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def list_quick_codes(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Quick Codes (POST /api/v2/quick_codes/list_quick_codes)."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_codes/list_quick_codes",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quick_codes/list_quick_codes"
    )


def update_quick_code(
    quick_code: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Quick Code (POST /api/v2/quick_codes/update_quick_code)."""
    request_json: dict[str, Any] = {"quick_code": quick_code}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_codes/update_quick_code",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quick_codes/update_quick_code"
    )


__all__ = [
    "list_quick_codes",
    "update_quick_code",
]
