"""BriteCore V2 quick_code_values API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def list_quick_code_values(
    quick_codes: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quick_code_values/list_quick_code_values``."""
    request_json: dict[str, Any] = {"quick_codes": quick_codes}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_code_values/list_quick_code_values",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quick_code_values/list_quick_code_values"
    )


def update_quick_code_value(
    quick_code_value: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quick_code_values/update_quick_code_value``."""
    request_json: dict[str, Any] = {"quick_code_value": quick_code_value}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_code_values/update_quick_code_value",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quick_code_values/update_quick_code_value"
    )


__all__ = [
    "list_quick_code_values",
    "update_quick_code_value",
]
