"""BriteCore V2 quick_quote_templates API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def add_template_to_policy_type(
    quick_quote_template_id: str | None = None,
    policy_type_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Add Template To Policy Type.

    Send a request to POST /api/v2/quick_quote_templates/add_template_to_policy_type. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "quick_quote_template_id": quick_quote_template_id,
        "policy_type_id": policy_type_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/add_template_to_policy_type",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/add_template_to_policy_type",
    )


def create_quick_quote_template(
    policy_type_ids: list[str] | None = None,
    quote_template: dict[str, Any] | None = None,
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Quick Quote Template.

    Send a request to POST /api/v2/quick_quote_templates/create_quick_quote_template. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "policy_type_ids": policy_type_ids,
        "quote_template": quote_template,
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/create_quick_quote_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/create_quick_quote_template",
    )


def create_template_risk_default_value(
    quick_quote_template_id: str | None = None,
    version: int | None = None,
    risk_type: str | None = None,
    risk_defaults: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Template Risk Default Value.

    Send a request to POST /api/v2/quick_quote_templates/create_template_risk_default_value. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "quick_quote_template_id": quick_quote_template_id,
        "version": version,
        "risk_type": risk_type,
        "risk_defaults": risk_defaults,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/create_template_risk_default_value",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/create_template_risk_default_value",
    )


def delete_quick_quote_template(
    template_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Quick Quote Template.

    Send a request to POST /api/v2/quick_quote_templates/delete_quick_quote_template. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "template_id": template_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/delete_quick_quote_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/delete_quick_quote_template",
    )


def delete_template_risk_default_value(
    value_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Template Risk Default Value.

    Send a request to POST /api/v2/quick_quote_templates/delete_template_risk_default_value. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "value_id": value_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/delete_template_risk_default_value",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/delete_template_risk_default_value",
    )


def get_quick_quote_template(
    template_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Quick Quote Template.

    Send a request to POST /api/v2/quick_quote_templates/get_quick_quote_template. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "template_id": template_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/get_quick_quote_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/get_quick_quote_template",
    )


def list_quick_quote_templates(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Quick Quote Templates.

    Send a request to POST /api/v2/quick_quote_templates/list_quick_quote_templates. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/list_quick_quote_templates",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/list_quick_quote_templates",
    )


def update_quick_quote_template(
    policy_type_ids: list[str] | None = None,
    quote_template: dict[str, Any] | None = None,
    template_risk_values: list[dict[str, Any]] | None = None,
    id: str | None = None,
    name: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Quick Quote Template.

    Send a request to POST /api/v2/quick_quote_templates/update_quick_quote_template. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "policy_type_ids": policy_type_ids,
        "quote_template": quote_template,
        "template_risk_values": template_risk_values,
        "id": id,
        "name": name,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/update_quick_quote_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/update_quick_quote_template",
    )


def update_template_risk_default_value(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Template Risk Default Value.

    Send a request to POST /api/v2/quick_quote_templates/update_template_risk_default_value. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quick_quote_templates/update_template_risk_default_value",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/quick_quote_templates/update_template_risk_default_value",
    )


__all__ = [
    "add_template_to_policy_type",
    "create_quick_quote_template",
    "create_template_risk_default_value",
    "delete_quick_quote_template",
    "delete_template_risk_default_value",
    "get_quick_quote_template",
    "list_quick_quote_templates",
    "update_quick_quote_template",
    "update_template_risk_default_value",
]
