"""BriteCore v2 Quotes API endpoint wrappers.

These wrappers cover quote creation and retrieval workflows exposed by the SDK's
current v2 quote surface. The quote paths remain known spec-gap wrappers, so the
docstrings describe the intended API contract first and call out SDK-specific
response normalization where needed.
"""

from logging import Logger
from typing import Any, Unpack

from urllib3 import BaseHTTPResponse, HTTPResponse, Timeout

from britecore_sdk import BritecoreError, logger
from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
    web_timeout_long,
)

LOGGER: Logger = logger

API_CLIENT: BritecoreAPIClient = api_client


def create_full_quote(
    quote_json: dict[str, Any], **kwargs: Unpack[RequestParameters]
) -> tuple[dict[str, Any] | None, str | None]:
    """Create a quote from the supplied quote payload.

    This wrapper submits ``quote_json`` to ``/api/v2/quotes/create_full_quote``
    and normalizes the response through ``process_result(...)``. As an SDK-
    specific convenience, it returns a tuple of ``(quote_data, quote_id)``,
    where ``quote_id`` is extracted from the normalized payload when present.
    ``**kwargs`` accepts ``RequestParameters`` overrides such as timeout,
    headers, or retry settings.

    Raises:
        BritecoreError.MissingParameter: If quote_json is missing or empty.
    """
    # Validate required parameters
    if not quote_json or not isinstance(quote_json, dict):
        raise BritecoreError.MissingParameter(
            "quote_json is required and must be a dict"
        )

    # Quote creation is a long-running write; apply the long timeout unless the
    # caller has already provided an explicit request_timeout override.
    provided_timeout: Timeout | None = kwargs.get("request_timeout")
    if not provided_timeout:
        kwargs.update({"request_timeout": Timeout(web_timeout_long)})

    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path="/api/v2/quotes/create_full_quote", json=quote_json, **kwargs
    )

    json_info: Any = API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/create_full_quote"
    )

    if not json_info:
        return None, None

    return json_info, json_info["id"]


def get_quote(quote_id: str, **kwargs: Unpack[RequestParameters]) -> Any:
    """Retrieve a quote by quote identifier.

    This wrapper sends ``quote_id`` to ``/api/v2/quotes/get_quote`` and returns the
    normalized ``process_result(...)`` payload for the requested quote.
    ``**kwargs`` accepts ``RequestParameters`` overrides such as timeout,
    headers, or retry settings.

    Raises:
        BritecoreError.MissingParameter: If quote_id is missing.
    """
    # Validate required parameters
    if not quote_id or not quote_id.strip():
        raise BritecoreError.MissingParameter("quote id is required")
    quote_json: dict[str, str] = {"id": quote_id}

    LOGGER.debug("Getting quote")

    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path="/api/v2/quotes/get_quote", json=quote_json, **kwargs
    )

    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/get_quote"
    )


__all__ = ["create_full_quote", "get_quote"]

# --- Autogenerated spec wrappers ---


def associate_agentcy_to_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/associate_agentcy_to_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/associate_agentcy_to_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/associate_agentcy_to_quote"
    )


def bind_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/bind_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/bind_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/bind_full_quote"
    )


def copy_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/copy_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/copy_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/copy_quote"
    )


def create_and_rate_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/create_and_rate_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/create_and_rate_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/create_and_rate_full_quote"
    )


def create_endorsement_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/create_endorsement_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/create_endorsement_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/create_endorsement_quote"
    )


def create_renewal_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/create_renewal_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/create_renewal_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/create_renewal_quote"
    )


def delete_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/delete_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/delete_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/delete_full_quote"
    )


def delete_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/delete_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/delete_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/delete_quote"
    )


def get_estimated_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/get_estimated_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/get_estimated_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/get_estimated_quote"
    )


def get_quote_properties_summary(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/get_quote_properties_summary``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/get_quote_properties_summary",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/get_quote_properties_summary"
    )


def get_quote_wizard_plugin(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/get_quote_wizard_plugin``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/get_quote_wizard_plugin",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/get_quote_wizard_plugin"
    )


def get_risks(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/get_risks``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/get_risks",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/get_risks"
    )


def issue_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/issue_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/issue_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/issue_full_quote"
    )


def list_available_offers(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/list_available_offers``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/list_available_offers",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/list_available_offers"
    )


def modify_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/modify_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/modify_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/modify_full_quote"
    )


def prefill_loss_history(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/prefill_loss_history``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/prefill_loss_history",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/prefill_loss_history"
    )


def prefill_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/prefill_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/prefill_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/prefill_quote"
    )


def prefill_violations(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/prefill_violations``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/prefill_violations",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/prefill_violations"
    )


def rate_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/rate_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/rate_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/rate_full_quote"
    )


def rate_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/rate_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/rate_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/rate_quote"
    )


def retrieve_full_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/retrieve_full_quote``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/retrieve_full_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/retrieve_full_quote"
    )


def submit_application(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/submit_application``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/submit_application",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/submit_application"
    )


def submit_change(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/submit_change``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/submit_change",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/submit_change"
    )


def summary(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/summary``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/summary",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(request_result, endpoint="/api/v2/quotes/summary")


def turn_quote_into_application(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/turn_quote_into_application``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/turn_quote_into_application",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/turn_quote_into_application"
    )


def update_e_delivery_enabled(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quotes/update_e_delivery_enabled``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/quotes/update_e_delivery_enabled",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/quotes/update_e_delivery_enabled"
    )


__all__.extend(
    [
        "associate_agentcy_to_quote",
        "bind_full_quote",
        "copy_quote",
        "create_and_rate_full_quote",
        "create_endorsement_quote",
        "create_renewal_quote",
        "delete_full_quote",
        "delete_quote",
        "get_estimated_quote",
        "get_quote_properties_summary",
        "get_quote_wizard_plugin",
        "get_risks",
        "issue_full_quote",
        "list_available_offers",
        "modify_full_quote",
        "prefill_loss_history",
        "prefill_quote",
        "prefill_violations",
        "rate_full_quote",
        "rate_quote",
        "retrieve_full_quote",
        "submit_application",
        "submit_change",
        "summary",
        "turn_quote_into_application",
        "update_e_delivery_enabled",
    ]
)
