"""BriteCore V2 quote API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---

def add_flow_placeholder(
    field: str | None = None,
    Returns: str | None = None,
    flow_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/add_flow_placeholder``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "-------": field,
        "Returns": Returns,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/add_flow_placeholder",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/add_flow_placeholder")


def add_quote_wizard_flow(
    policy_type_id: Any | None = None,
    is_endorsement: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/add_quote_wizard_flow``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "policy_type_id": policy_type_id,
        "is_endorsement": is_endorsement,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/add_quote_wizard_flow",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/add_quote_wizard_flow")


def add_wizard_flow_section(
    section_name: Any | None = None,
    flow_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/add_wizard_flow_section``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "section_name": section_name,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/add_wizard_flow_section",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/add_wizard_flow_section")


def batch_update_flow_sections(
    section_list: Any | None = None,
    flow_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/batch_update_flow_sections``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "section_list": section_list,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/batch_update_flow_sections",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/batch_update_flow_sections")


def create_flow_from_quote_flow(
    quote_flow_id: Any | None = None,
    admin: Any | None = None,
    endorsement: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/create_flow_from_quote_flow``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "quote_flow_id": quote_flow_id,
        "admin": admin,
        "endorsement": endorsement,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/create_flow_from_quote_flow",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/create_flow_from_quote_flow")


def delete_quote_wizard_flow(
    id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/delete_quote_wizard_flow``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "id": id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/delete_quote_wizard_flow",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/delete_quote_wizard_flow")


def get_flow_features(
    field: str | None = None,
    Returns: str | None = None,
    flow_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_flow_features``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "-------": field,
        "Returns": Returns,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_flow_features",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_flow_features")


def get_flow_placeholders(
    field: str | None = None,
    Returns: str | None = None,
    flow_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_flow_placeholders``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "-------": field,
        "Returns": Returns,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_flow_placeholders",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_flow_placeholders")


def get_property_quote_integration_dependencies(
    integration_id: str | None = None,
    property_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_property_quote_integration_dependencies``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "integration_id": integration_id,
        "property_id": property_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_property_quote_integration_dependencies",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_property_quote_integration_dependencies")


def get_quote_wizard_flow(
    field: str | None = None,
    policy_type_id: str | None = None,
    Returns: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_quote_wizard_flow``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "-------": field,
        "policy_type_id": policy_type_id,
        "Returns": Returns,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_quote_wizard_flow",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_quote_wizard_flow")


def get_quote_wizard_flows(
    include: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_quote_wizard_flows``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "include": include,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_quote_wizard_flows",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_quote_wizard_flows")


def get_wizard_flow_sections(
    flow_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/get_wizard_flow_sections``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/get_wizard_flow_sections",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/get_wizard_flow_sections")


def patch_flow_definition(
    definition: Any | None = None,
    is_endorsement: Any | None = None,
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/patch_flow_definition``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "definition": definition,
        "is_endorsement": is_endorsement,
        "id": id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/patch_flow_definition",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/patch_flow_definition")


def patch_flow_feature_attribute(
    attr_dict: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/patch_flow_feature_attribute``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "attr_dict": attr_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/patch_flow_feature_attribute",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/patch_flow_feature_attribute")


def patch_flow_features(
    feature_dict: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/patch_flow_features``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "feature_dict": feature_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/patch_flow_features",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/patch_flow_features")


def patch_placeholder(
    field: str | None = None,
    Returns: str | None = None,
    placeholder_dict: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/patch_placeholder``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "-------": field,
        "Returns": Returns,
        "placeholder_dict": placeholder_dict,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/patch_placeholder",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/patch_placeholder")


def remove_wizard_flow_section(
    section_name: Any | None = None,
    flow_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/quote/remove_wizard_flow_section``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "section_name": section_name,
        "flow_id": flow_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/quote/remove_wizard_flow_section",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/quote/remove_wizard_flow_section")


__all__ = [
    "add_flow_placeholder",
    "add_quote_wizard_flow",
    "add_wizard_flow_section",
    "batch_update_flow_sections",
    "create_flow_from_quote_flow",
    "delete_quote_wizard_flow",
    "get_flow_features",
    "get_flow_placeholders",
    "get_property_quote_integration_dependencies",
    "get_quote_wizard_flow",
    "get_quote_wizard_flows",
    "get_wizard_flow_sections",
    "patch_flow_definition",
    "patch_flow_feature_attribute",
    "patch_flow_features",
    "patch_placeholder",
    "remove_wizard_flow_section",
]
