"""BriteCore v2 Return Premium API endpoint wrappers.

This module provides the SDK wrapper for exporting return premium records from
the BriteCore v2 return premium API.
"""

from logging import Logger
from typing import Any, Unpack, cast

from urllib3 import BaseHTTPResponse, HTTPResponse

from britecore_sdk import logger
from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

LOGGER: Logger = logger

API_CLIENT: BritecoreAPIClient = api_client


def build_payload(**fields: Any) -> dict[str, Any]:
    """Build a JSON payload, omitting keys whose value is ``None``."""
    return {key: value for key, value in fields.items() if value is not None}


def post(
    path: str,
    payload: dict[str, Any] | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Send a return_premium request and normalize the response."""
    LOGGER.debug("Calling return_premium endpoint %s", path)
    request_result: BaseHTTPResponse | HTTPResponse | None = API_CLIENT.do_request(
        path=path,
        json=payload if payload is not None else {},
        **kwargs,
    )
    return API_CLIENT.process_result(cast(Any, request_result))


def exportreturnpremium(
    return_premium_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Export a return premium record by identifier.

    This wrapper sends ``return_premium_id`` as ``returnPremiumId`` to
    ``/api/v2/return_premium/exportReturnPremium`` and returns the normalized
    ``process_result(...)`` payload for the export operation. ``**kwargs``
    accepts ``RequestParameters`` overrides.
    """
    payload: dict[str, Any] = {}
    if return_premium_id is not None:
        payload["returnPremiumId"] = return_premium_id
    return post(
        "/api/v2/return_premium/exportReturnPremium",
        payload,
        **kwargs,
    )


__all__ = [
    "exportreturnpremium",
]

# --- Autogenerated spec wrappers ---


def retrieve_return_premiums(
    authorized: bool | None = None,
    transferred: bool | None = None,
    rejected: bool | None = None,
    voided: bool | None = None,
    canceled: bool | None = None,
    from_date: str | None = None,
    exported: bool | None = None,
    policy_type_ids: list[str] | None = None,
    to_date: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve Return Premiums.

    Send a request to POST /api/v2/return_premium/retrieve_return_premiums. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "authorized": authorized,
        "transferred": transferred,
        "rejected": rejected,
        "voided": voided,
        "canceled": canceled,
        "from_date": from_date,
        "exported": exported,
        "policy_type_ids": policy_type_ids,
        "to_date": to_date,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/return_premium/retrieve_return_premiums",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/return_premium/retrieve_return_premiums"
    )


__all__.extend(
    [
        "retrieve_return_premiums",
    ]
)
