"""BriteCore v2 Signatures API endpoint wrappers.

This module provides wrappers for DocuSign authentication, configuration,
signature retrieval, envelope recreation, and envelope status updates.
"""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters
from britecore_sdk.api.api_calls.v2._common import build_payload, post


def docusign_auth(
    action: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Perform a DocuSign authentication action.

    This wrapper sends ``action`` to ``/api/v2/signatures/docusign_auth`` and
    returns the normalized ``process_result(...)`` payload for the DocuSign
    authentication workflow. ``**kwargs`` accepts ``RequestParameters``
    overrides.
    """
    return post(
        "/api/v2/signatures/docusign_auth",
        build_payload(action=action),
        **kwargs,
    )


def docusign_config(
    data: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve or update DocuSign configuration.

    This wrapper sends the optional ``data`` payload to
    ``/api/v2/signatures/docusign_config`` and returns the normalized
    ``process_result(...)`` payload for the DocuSign configuration record.
    ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    return post(
        "/api/v2/signatures/docusign_config",
        build_payload(data=data),
        **kwargs,
    )


def get_signatures(
    revision_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Retrieve signature records for a revision.

    This wrapper sends ``revision_id`` to ``/api/v2/signatures/get_signatures``
    and returns the normalized ``process_result(...)`` payload for the matching
    signature records. ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    return post(
        "/api/v2/signatures/get_signatures",
        build_payload(revision_id=revision_id),
        **kwargs,
    )


def recreate_envelope(
    revision_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Recreate a DocuSign envelope for a revision.

    This wrapper sends ``revision_id`` to
    ``/api/v2/signatures/recreate_envelope`` and returns the normalized
    ``process_result(...)`` payload for the recreated envelope.
    ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    return post(
        "/api/v2/signatures/recreate_envelope",
        build_payload(revision_id=revision_id),
        **kwargs,
    )


def update_signatures(
    envelope_id: str | None = None,
    signers: str | None = None,
    status: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update signature records for an envelope.

    This wrapper sends ``envelope_id``, ``signers``, and ``status`` to
    ``/api/v2/signatures/update_signatures`` and returns the normalized
    ``process_result(...)`` payload for the update request. ``**kwargs``
    accepts ``RequestParameters`` overrides.
    """
    return post(
        "/api/v2/signatures/update_signatures",
        build_payload(envelope_id=envelope_id, signers=signers, status=status),
        **kwargs,
    )


def void_envelope(
    envelope_id: Any | None = None,
    revision_id: Any | None = None,
    void_reason: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Void a DocuSign envelope.

    This wrapper sends the envelope identifier, optional revision identifier,
    and optional ``void_reason`` to ``/api/v2/signatures/void_envelope`` and
    returns the normalized ``process_result(...)`` payload for the void
    request. ``**kwargs`` accepts ``RequestParameters`` overrides.
    """
    payload: dict[str, Any] = {}
    if envelope_id is not None:
        payload["envelopeId"] = envelope_id
    if revision_id is not None:
        payload["revisionId"] = revision_id
    if void_reason is not None:
        payload["voidReason"] = void_reason
    return post("/api/v2/signatures/void_envelope", payload, **kwargs)


__all__ = [
    "docusign_auth",
    "docusign_config",
    "get_signatures",
    "recreate_envelope",
    "update_signatures",
    "void_envelope",
]

# --- Autogenerated spec wrappers ---


def flush_cache(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/signatures/flush_cache``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/signatures/flush_cache",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/signatures/flush_cache"
    )


def get_envelope(
    revision_id: Any | None = None,
    envelope_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/signatures/get_envelope``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {
        "revision_id": revision_id,
        "envelope_id": envelope_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/signatures/get_envelope",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/signatures/get_envelope"
    )


__all__.extend(
    [
        "flush_cache",
        "get_envelope",
    ]
)
