"""BriteCore V2 statement_of_value API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_sov(
    sov_import: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/create_sov``."""
    request_json: dict[str, Any] = {"sov_import": sov_import}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/create_sov",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/create_sov"
    )


def delete_sov(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/delete_sov``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/delete_sov",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/delete_sov"
    )


def delete_sov_file(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/delete_sov_file``."""
    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/delete_sov_file",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/delete_sov_file"
    )


def execute_sov_job(
    sov_import_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/execute_sov_job``."""
    request_json: dict[str, Any] = {"sov_import_id": sov_import_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/execute_sov_job",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/execute_sov_job"
    )


def export_sov_template(
    policy_type_id: Any | None = None,
    policy_numbers: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/export_sov_template``."""
    request_json: dict[str, Any] = {
        "policy_type_id": policy_type_id,
        "policy_numbers": policy_numbers,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/export_sov_template",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/export_sov_template"
    )


def get_policies_from_sov(
    page: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/get_policies_from_sov``."""
    request_json: dict[str, Any] = {"page": page}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/get_policies_from_sov",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/get_policies_from_sov"
    )


def get_sov_info(
    sov_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/get_sov_info``."""
    request_json: dict[str, Any] = {"sov_id": sov_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/get_sov_info",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/get_sov_info"
    )


def get_sovs(
    page: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/get_sovs``."""
    request_json: dict[str, Any] = {"page": page}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/get_sovs",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/get_sovs"
    )


def update_elastic_search_index(
    policy_ids: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/update_elastic_search_index``."""
    request_json: dict[str, Any] = {"policy_ids": policy_ids}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/update_elastic_search_index",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result,
        endpoint="/api/v2/statement_of_value/update_elastic_search_index",
    )


def update_sov(
    sov_import: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/update_sov``."""
    request_json: dict[str, Any] = {"sov_import": sov_import}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/update_sov",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/update_sov"
    )


def validate_sov(
    sov_import_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/statement_of_value/validate_sov``."""
    request_json: dict[str, Any] = {"sov_import_id": sov_import_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/statement_of_value/validate_sov",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/statement_of_value/validate_sov"
    )


__all__ = [
    "create_sov",
    "delete_sov",
    "delete_sov_file",
    "execute_sov_job",
    "export_sov_template",
    "get_policies_from_sov",
    "get_sov_info",
    "get_sovs",
    "update_elastic_search_index",
    "update_sov",
    "validate_sov",
]
