"""BriteCore V2 term_credit_scores API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def get_options(
    revision_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Options.

    POST /api/v2/term_credit_scores/get_options
    """
    request_json: dict[str, Any] = {
        "revision_id": revision_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/term_credit_scores/get_options",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/term_credit_scores/get_options"
    )


def update_selection(
    revision_id: str | None = None,
    selected_option: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Selection.

    POST /api/v2/term_credit_scores/update_selection
    """
    request_json: dict[str, Any] = {
        "revision_id": revision_id,
        "selected_option": selected_option,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/term_credit_scores/update_selection",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/term_credit_scores/update_selection"
    )


__all__ = [
    "get_options",
    "update_selection",
]
