"""BriteCore V2 term_credit_scores API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---

def get_options(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/term_credit_scores/get_options``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/term_credit_scores/get_options",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/term_credit_scores/get_options")


def update_selection(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/term_credit_scores/update_selection``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/term_credit_scores/update_selection",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(request_result, endpoint="/api/v2/term_credit_scores/update_selection")


__all__ = [
    "get_options",
    "update_selection",
]
