"""BriteCore V2 vehicles API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import RequestParameters

# --- Autogenerated spec wrappers ---


def add_additional_interest(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/add_additional_interest``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/add_additional_interest",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/add_additional_interest"
    )


def check_vehicle_prefill_fallback_configured(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/check_vehicle_prefill_fallback_configured``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/check_vehicle_prefill_fallback_configured",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result,
        endpoint="/api/v2/vehicles/check_vehicle_prefill_fallback_configured",
    )


def create_vehicle(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/create_vehicle``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/create_vehicle",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/create_vehicle"
    )


def delete_additional_interest(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/delete_additional_interest``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/delete_additional_interest",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/delete_additional_interest"
    )


def delete_vehicle(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/delete_vehicle``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/delete_vehicle",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/delete_vehicle"
    )


def get_additional_interest(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/get_additional_interest``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/get_additional_interest",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/get_additional_interest"
    )


def get_vehicle(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/get_vehicle``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/get_vehicle",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/get_vehicle"
    )


def list_additional_interests_for_vehicle(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/list_additional_interests_for_vehicle``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/list_additional_interests_for_vehicle",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result,
        endpoint="/api/v2/vehicles/list_additional_interests_for_vehicle",
    )


def list_custom_fields_types(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/list_custom_fields_types``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/list_custom_fields_types",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/list_custom_fields_types"
    )


def list_vehicles_for_quote(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/list_vehicles_for_quote``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/list_vehicles_for_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/list_vehicles_for_quote"
    )


def update_additional_interest(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/update_additional_interest``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/update_additional_interest",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/update_additional_interest"
    )


def update_vehicle(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/update_vehicle``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/update_vehicle",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/update_vehicle"
    )


def vehicle_prefill_fallback(
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Autogenerated wrapper for ``POST /api/v2/vehicles/vehicle_prefill_fallback``."""
    from britecore_sdk.api.api_calls import api_client as _api_client

    request_json: dict[str, Any] = {}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = _api_client.do_request(
        path="/api/v2/vehicles/vehicle_prefill_fallback",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return _api_client.process_result(
        request_result, endpoint="/api/v2/vehicles/vehicle_prefill_fallback"
    )


__all__ = [
    "add_additional_interest",
    "check_vehicle_prefill_fallback_configured",
    "create_vehicle",
    "delete_additional_interest",
    "delete_vehicle",
    "get_additional_interest",
    "get_vehicle",
    "list_additional_interests_for_vehicle",
    "list_custom_fields_types",
    "list_vehicles_for_quote",
    "update_additional_interest",
    "update_vehicle",
    "vehicle_prefill_fallback",
]
