"""BriteCore V2 violations API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_driver_mvr_report_file(
    driver_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Driver Mvr Report File.

    Send a request to POST /api/v2/violations/create_driver_mvr_report_file. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"driver_id": driver_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/create_driver_mvr_report_file",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/create_driver_mvr_report_file"
    )


def create_violation(
    violation: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Violation.

    Send a request to POST /api/v2/violations/create_violation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"violation": violation}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/create_violation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/create_violation"
    )


def create_violations(
    violations: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Violations.

    Send a request to POST /api/v2/violations/create_violations. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"violations": violations}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/create_violations",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/create_violations"
    )


def delete_violation(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Violation.

    Send a request to POST /api/v2/violations/delete_violation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/delete_violation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/delete_violation"
    )


def dispute_violation(
    violation_dispute: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Dispute Violation.

    Send a request to POST /api/v2/violations/dispute_violation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"violation_dispute": violation_dispute}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/dispute_violation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/dispute_violation"
    )


def get_violation(
    id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Violation.

    Send a request to POST /api/v2/violations/get_violation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"id": id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/get_violation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/get_violation"
    )


def list_violation_for_driver(
    driver_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Violation For Driver.

    Send a request to POST /api/v2/violations/list_violation_for_driver. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"driver_id": driver_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/list_violation_for_driver",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/list_violation_for_driver"
    )


def remove_violation_dispute(
    violation_id: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Remove Violation Dispute.

    Send a request to POST /api/v2/violations/remove_violation_dispute. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"violation_id": violation_id}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/remove_violation_dispute",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/remove_violation_dispute"
    )


def update_violation(
    violation: Any | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Violation.

    Send a request to POST /api/v2/violations/update_violation. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {"violation": violation}
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/violations/update_violation",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/violations/update_violation"
    )


__all__ = [
    "create_driver_mvr_report_file",
    "create_violation",
    "create_violations",
    "delete_violation",
    "dispute_violation",
    "get_violation",
    "list_violation_for_driver",
    "remove_violation_dispute",
    "update_violation",
]
