"""BriteCore V2 watercrafts API endpoint wrappers."""

from typing import Any, Unpack

from britecore_sdk.api.api_calls import (
    BritecoreAPIClient,
    RequestParameters,
    api_client,
)

API_CLIENT: BritecoreAPIClient = api_client

# --- Autogenerated spec wrappers ---


def create_watercraft(
    watercraft: dict[str, Any] | None = None,
    skip_rules: bool | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Create Watercraft.

    Send a request to POST /api/v2/watercrafts/create_watercraft. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "watercraft": watercraft,
        "skip_rules": skip_rules,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/create_watercraft",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/create_watercraft"
    )


def delete_watercraft(
    id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Delete Watercraft.

    Send a request to POST /api/v2/watercrafts/delete_watercraft. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "id": id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/delete_watercraft",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/delete_watercraft"
    )


def get_watercraft(
    id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Get Watercraft.

    Send a request to POST /api/v2/watercrafts/get_watercraft. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "id": id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/get_watercraft",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/get_watercraft"
    )


def list_custom_fields_types(
    quote_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Custom Fields Types.

    Send a request to POST /api/v2/watercrafts/list_custom_fields_types. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "quote_id": quote_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/list_custom_fields_types",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/list_custom_fields_types"
    )


def list_watercrafts_for_quote(
    quote_id: str | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """List Watercrafts For Quote.

    Send a request to POST /api/v2/watercrafts/list_watercrafts_for_quote. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "quote_id": quote_id,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/list_watercrafts_for_quote",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/list_watercrafts_for_quote"
    )


def update_watercraft(
    watercraft: dict[str, Any] | None = None,
    skip_rules: bool | None = None,
    **kwargs: Unpack[RequestParameters],
) -> Any:
    """Update Watercraft.

    Send a request to POST /api/v2/watercrafts/update_watercraft. Returns processed result from
    ``process_result(...)`` and accepts ``RequestParameters`` overrides.

    Args:
        **kwargs: Additional request parameters (timeout, retry, headers, dry_run, etc.).

    Returns:
        Any: The processed response containing the requested data.

    Raises:
        BritecoreError: Various exceptions from process_result if the API returns an error.
    """
    request_json: dict[str, Any] = {
        "watercraft": watercraft,
        "skip_rules": skip_rules,
    }
    filtered_json = {k: v for k, v in request_json.items() if v is not None}
    request_result = API_CLIENT.do_request(
        path="/api/v2/watercrafts/update_watercraft",
        json=filtered_json,
        method="POST",
        **kwargs,
    )
    return API_CLIENT.process_result(
        request_result, endpoint="/api/v2/watercrafts/update_watercraft"
    )


__all__ = [
    "create_watercraft",
    "delete_watercraft",
    "get_watercraft",
    "list_custom_fields_types",
    "list_watercrafts_for_quote",
    "update_watercraft",
]
