<#
.SYNOPSIS
    Remove regenerable local artifacts from the repository.

.DESCRIPTION
    Cleans common generated outputs and Python caches from this repository.
    This script is safe by default and keeps virtual environments unless you
    explicitly include them.

.PARAMETER IncludeVirtualEnvs
    Also remove local virtual environments (`.venv` and `env`).

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\scripts\clean.ps1

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\scripts\clean.ps1 -WhatIf

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File .\scripts\clean.ps1 -IncludeVirtualEnvs
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [Parameter()]
    [switch]$IncludeVirtualEnvs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot

$removedPaths = [System.Collections.Generic.List[string]]::new()
$removedFiles = 0

function Remove-PathIfExists {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,

        [Parameter(Mandatory = $true)]
        [string]$Reason
    )

    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    if ($PSCmdlet.ShouldProcess($Path, "Remove $Reason")) {
        Remove-Item -LiteralPath $Path -Recurse -Force
        $script:removedPaths.Add($Path) | Out-Null
    }
}

Write-Host "Repository root: $RepoRoot"

# Top-level generated directories.
$topLevelDirs = @(
    "build",
    "dist",
    "htmlcov",
    "docs\_build",
    ".pytest_cache",
    ".mypy_cache"
)

if ($IncludeVirtualEnvs) {
    $topLevelDirs += @(".venv", "env")
}

foreach ($dir in $topLevelDirs) {
    Remove-PathIfExists -Path (Join-Path $RepoRoot $dir) -Reason "generated directory"
}

# Remove any egg-info directories from repo root.
Get-ChildItem -Path $RepoRoot -Directory -Filter "*.egg-info" -Force -ErrorAction SilentlyContinue |
    ForEach-Object {
        Remove-PathIfExists -Path $_.FullName -Reason "egg-info metadata"
    }

# Remove Python bytecode caches recursively.
Get-ChildItem -Path $RepoRoot -Directory -Recurse -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -eq "__pycache__" } |
    ForEach-Object {
        if ($PSCmdlet.ShouldProcess($_.FullName, "Remove Python cache directory")) {
            Remove-Item -LiteralPath $_.FullName -Recurse -Force
            $removedFiles++
        }
    }

Get-ChildItem -Path $RepoRoot -File -Recurse -Force -ErrorAction SilentlyContinue |
    Where-Object { $_.Extension -in @(".pyc", ".pyo") } |
    ForEach-Object {
        if ($PSCmdlet.ShouldProcess($_.FullName, "Remove Python bytecode file")) {
            Remove-Item -LiteralPath $_.FullName -Force
            $removedFiles++
        }
    }

# Coverage outputs are regenerated by test runs.
$coverageFiles = @(".coverage", "coverage.xml")
foreach ($file in $coverageFiles) {
    $fullPath = Join-Path $RepoRoot $file
    if (Test-Path -LiteralPath $fullPath) {
        if ($PSCmdlet.ShouldProcess($fullPath, "Remove coverage artifact")) {
            Remove-Item -LiteralPath $fullPath -Force
            $removedFiles++
        }
    }
}

Write-Host ""
Write-Host "Cleanup complete."
Write-Host "Removed directories: $($removedPaths.Count)"
if ($removedPaths.Count -gt 0) {
    $removedPaths | Sort-Object | ForEach-Object { Write-Host "  - $_" }
}
Write-Host "Removed files/directories from recursive cache pass: $removedFiles"
