"""Add API_CLIENT alias to autogenerated files missing it (F821 fix)."""

import pathlib

TARGET_IMPORT = "from britecore_sdk.api.api_calls import RequestParameters"
FULL_IMPORT = (
    "from britecore_sdk.api.api_calls import (\n"
    "    BritecoreAPIClient,\n"
    "    RequestParameters,\n"
    "    api_client,\n"
    ")\n"
    "\n"
    "API_CLIENT: BritecoreAPIClient = api_client"
)

# Files that only import RequestParameters and now need API_CLIENT
bad_files = [
    "src/britecore_sdk/api/api_calls/v1/deliverables.py",
    "src/britecore_sdk/api/api_calls/v1/notes.py",
    "src/britecore_sdk/api/api_calls/v1/policies.py",
    "src/britecore_sdk/api/api_calls/v1/reports.py",
    "src/britecore_sdk/api/api_calls/v2/agentcy.py",
    "src/britecore_sdk/api/api_calls/v2/attachments.py",
    "src/britecore_sdk/api/api_calls/v2/auth.py",
    "src/britecore_sdk/api/api_calls/v2/authority_limits.py",
    "src/britecore_sdk/api/api_calls/v2/background_jobs.py",
    "src/britecore_sdk/api/api_calls/v2/claim_adjuster_assignment_configs.py",
    "src/britecore_sdk/api/api_calls/v2/claim_catastrophes.py",
    "src/britecore_sdk/api/api_calls/v2/claim_changes.py",
    "src/britecore_sdk/api/api_calls/v2/claim_contacts.py",
    "src/britecore_sdk/api/api_calls/v2/claim_dates.py",
    "src/britecore_sdk/api/api_calls/v2/claim_estimations.py",
    "src/britecore_sdk/api/api_calls/v2/claim_exposures.py",
    "src/britecore_sdk/api/api_calls/v2/claim_injuries.py",
    "src/britecore_sdk/api/api_calls/v2/claim_properties.py",
    "src/britecore_sdk/api/api_calls/v2/claim_vehicles.py",
    "src/britecore_sdk/api/api_calls/v2/commissions.py",
    "src/britecore_sdk/api/api_calls/v2/configurations.py",
    "src/britecore_sdk/api/api_calls/v2/coverages.py",
    "src/britecore_sdk/api/api_calls/v2/custom_data.py",
    "src/britecore_sdk/api/api_calls/v2/data.py",
    "src/britecore_sdk/api/api_calls/v2/disputes.py",
    "src/britecore_sdk/api/api_calls/v2/drivers.py",
    "src/britecore_sdk/api/api_calls/v2/files.py",
    "src/britecore_sdk/api/api_calls/v2/geometries.py",
    "src/britecore_sdk/api/api_calls/v2/geometry.py",
    "src/britecore_sdk/api/api_calls/v2/imports.py",
    "src/britecore_sdk/api/api_calls/v2/ingestion_job.py",
    "src/britecore_sdk/api/api_calls/v2/integrations.py",
    "src/britecore_sdk/api/api_calls/v2/named_insureds.py",
    "src/britecore_sdk/api/api_calls/v2/permissions.py",
    "src/britecore_sdk/api/api_calls/v2/policy_types.py",
    "src/britecore_sdk/api/api_calls/v2/premium_finance_companies.py",
    "src/britecore_sdk/api/api_calls/v2/prior_policies.py",
    "src/britecore_sdk/api/api_calls/v2/quick_code_values.py",
    "src/britecore_sdk/api/api_calls/v2/quick_codes.py",
    "src/britecore_sdk/api/api_calls/v2/quick_quote_templates.py",
    "src/britecore_sdk/api/api_calls/v2/quote.py",
    "src/britecore_sdk/api/api_calls/v2/related_policies.py",
    "src/britecore_sdk/api/api_calls/v2/rules.py",
    "src/britecore_sdk/api/api_calls/v2/settings.py",
    "src/britecore_sdk/api/api_calls/v2/signatures.py",
    "src/britecore_sdk/api/api_calls/v2/statement_of_value.py",
    "src/britecore_sdk/api/api_calls/v2/subjectivities.py",
    "src/britecore_sdk/api/api_calls/v2/suspensions.py",
    "src/britecore_sdk/api/api_calls/v2/tasks.py",
    "src/britecore_sdk/api/api_calls/v2/term_credit_scores.py",
    "src/britecore_sdk/api/api_calls/v2/user_groups.py",
    "src/britecore_sdk/api/api_calls/v2/vehicles.py",
    "src/britecore_sdk/api/api_calls/v2/vendors.py",
    "src/britecore_sdk/api/api_calls/v2/violations.py",
    "src/britecore_sdk/api/api_calls/v2/watercrafts.py",
]


def fix_file(path: str) -> None:
    """Ensure a wrapper module has both API client imports and API_CLIENT alias."""
    f = pathlib.Path(path)
    text = f.read_text(encoding="utf-8")
    if "API_CLIENT" in text and "api_client" in text:
        print(f"  already ok: {f.name}")
        return
    if TARGET_IMPORT not in text:
        # Simpler: just add import + alias after the existing import block
        # Find end of import block
        lines = text.splitlines(keepends=True)
        insert_after = 0
        for i, line in enumerate(lines):
            if "from britecore_sdk.api.api_calls" in line:
                # Find the end of this import (may be multi-line)
                j = i
                while j < len(lines) and (
                    lines[j].startswith(" ")
                    or lines[j].startswith("from")
                    or lines[j].strip().endswith(",")
                ):
                    j += 1
                insert_after = j
                break
        # Insert after the import block
        new_lines = (
            lines[:insert_after]
            + [
                "from britecore_sdk.api.api_calls import BritecoreAPIClient, api_client\n",
                "\n",
                "API_CLIENT: BritecoreAPIClient = api_client\n",
            ]
            + lines[insert_after:]
        )
        f.write_text("".join(new_lines), encoding="utf-8")
        print(f"  inserted new import block: {f.name}")
        return

    # Simple case: replace the single-line RequestParameters import
    new_text = text.replace(TARGET_IMPORT, FULL_IMPORT)
    f.write_text(new_text, encoding="utf-8")
    print(f"  ok: {f.name}")


for p in bad_files:
    fix_file(p)

print("\nDone.")
